### PR TITLE
Convergence large outflow from small basin

### PR DESCRIPTION
**Pull request by SouthEndMusic**
Fixes https://github.com/Deltares/Ribasim/issues/1414

### CODE REVIEW

**Comment by SouthEndMusic** [comment]
Interesting results for this PR with the new `Crystal` test model provided by @fati-mon (now part of our test models):

Runtime new branch: ~3.1 seconds
Run current main: Several minutes

**Review by evetion — COMMENTED** [review]
Looking good already based on all the previous discussions! I would advise to keep it as simple as possible first, which IMHO would be using storage (instead of level) everywhere and setting both thresholds to zero. From there on we can experiment if needed, but probably first investigate why other models are unstable. 

Also, we probably should remove `isoutofdomain`, not sure how that interferes with the root finding of this continuouscallback.

**Comment by SouthEndMusic** [comment]
Closed in favor of https://github.com/Deltares/Ribasim/pull/1697

**Comment by visr** [comment]
This code could be useful in the future, but #1697 will do for a little while :)

**Pull request closed without merging**
