### PR TITLE
Remove osx64 from pixi

### LINKED ISSUE #1762: Update QGIS in conda to use the qgis_ltr label
**What**
We want the QGIS version to be installed to be the LTR versions that is published by conda-forge.

**Why**
This makes it possible to test against the lowest supported version.

**How**
We need to change the pixi channels like so:

```toml
channels = ["conda-forge/label/qgis_ltr", "conda-forge"]
```

**Additional context**
Although super easy to make this change, I made this into an issue because I got a bug when running `pixi update`.

> 
>   ⠁ py312:win-64         [00:00:03] resolving conda
>   ⠉ py312:osx-64         [00:00:03] [━━━━━━━━━━━━━━━━━━━━] 30.96 MiB @ 9.35 MiB/s downloading repodata
>   ⠉ py311:win-64         [00:00:03] resolving conda
>   ⠉ py311:osx-64         [00:00:03] loading repodata
>   ⠉ py311:osx-arm64      [00:00:03] resolving conda
>   ⠉ py311:linux-64       [00:00:03] resolving conda
>   ⠉ py312:linux-64       [00:00:03] resolving conda
>   ⠉ py310:osx-64         [00:00:03] loading repodata
>   ⠁ py310:linux-64       [00:00:03] resolving conda
>   ⠁ py310:osx-arm64      [00:00:03] resolving conda
>   ⠁ py310:win-64         [00:00:03] resolving conda                                                                       x failed to solve the conda requirements of 'py312' 'osx-arm64'
>   `-> Cannot solve the request because of: No candidates were found for build *.

See #1763 for that issue.

### PR DESCRIPTION
**Pull request by deltamarnix**
Does not fix #1762 anymore, but we don't use osx64 anymore, so we can remove it.

### CODE REVIEW

**Comment by deltamarnix** [comment]
# Explicit dependencies

|Dependency[^1]|Before|After|Change|Environments|
|-|-|-|-|-|
|**gh**|2.54.0|2.55.0|Minor Upgrade|dev on *all platforms*|
|**juliaup**|1.14.9|1.17.2|Minor Upgrade|dev on *all platforms*|
|**ruff**|0.5.7|0.6.2|Minor Upgrade|dev on *all platforms*|
|**qgis**[^2]|3.38.1|3.34.9|Minor Downgrade|dev on osx-64|
|**qgis**[^2]|3.38.1|3.34.10|Minor Downgrade|dev on {linux-64, osx-arm64, win-64}|
|**ipywidgets**|8.1.3|8.1.5|Patch Upgrade|*all*|
|**jupyterlab**|4.2.4|4.2.5|Patch Upgrade|dev on *all platforms*|
|**libgdal-arrow-parquet**|3.9.1|3.9.2|Patch Upgrade|dev on *all platforms*|
|**matplotlib**|3.9.1|3.9.2|Patch Upgrade|*all envs* on {osx-64, osx-arm64}<br/>{py310, py311} on {linux-64, win-64}|
|**minio**|7.2.7|7.2.8|Patch Upgrade|*all*|
|**mypy**|1.11.1|1.11.2|Patch Upgrade|dev on *all platforms*|
|**numpy**|2.0.1|2.0.2|Patch Upgrade|*all*|
|**quartodoc**|0.7.5|0.7.6|Patch Upgrade|dev on *all platforms*|
|**shapely**|2.0.5|2.0.6|Patch Upgrade|*all*|
|**xugrid**|0.11.0|0.11.2|Patch Upgrade|*all*|
|**pandera**|hd8ed1ab_0|hd8ed1ab_1|Only build string|*all*|

# Implicit dependencies

|Dependency[^1]|Before|After|Change|Environments|
|-|-|-|-|-|
|libegl||1.7.0|Added|{py310, py311} on linux-64|
|libflang||5.0.0|Added|dev on win-64|
|libgl||1.7.0|Added|{py310, py311} on linux-64|
|libglvnd||1.7.0|Added|{py310, py311} on linux-64|
|libglx||1.7.0|Added|{py310, py311} on linux-64|
|llvm-meta||5.0.0|Added|dev on win-64|
|metis||5.1.0|Added|dev on win-64|
|openmp||5.0.0|Added|dev on win-64|
|suitesparse||7.8.2|Added|dev on win-64|
|xorg-fixesproto||5.0|Added|{py310, py311} on linux-64|
|xorg-inputproto||2.3.2|Added|{py310, py311} on linux-64|
|xorg-libxfixes||5.0.3|Added|{py310, py311} on linux-64|
|xorg-libxi||1.7.10|Added|{py310, py311} on linux-64|
|xorg-libxtst||1.2.5|Added|{py310, py311} on linux-64|
|xorg-libxxf86vm||1.1.5|Added|{py310, py311} on linux-64|
|xorg-recordproto||1.14.2|Added|{py310, py311} on linux-64|
|griffe|0.48.0|1.2.0|Major Upgrade|dev on *all platforms*|
|mysql-common|8.3.0|9.0.1|Major Upgrade|{py310, py311} on linux-64|
|mysql-libs|8.3.0|9.0.1|Major Upgrade|{py310, py311} on linux-64|
|black|24.4.2|24.8.0|Minor Upgrade|*all*|
|c-ares|1.32.3|1.33.1|Minor Upgrade|*all*|
|esbuild|0.19.2|0.23.1|Minor Upgrade|dev on *all platforms*|
|idna|3.7|3.8|Minor Upgrade|*all*|
|importlib-metadata|8.2.0|8.4.0|Minor Upgrade|*all*|
|importlib_metadata|8.2.0|8.4.0|Minor Upgrade|*all*|
|libgoogle-cloud|2.26.0|2.28.0|Minor Upgrade|*all*|
|libgoogle-cloud-storage|2.26.0|2.28.0|Minor Upgrade|*all*|
|libthrift|0.19.0|0.20.0|Minor Upgrade|*all*|
|lxml|5.2.2|5.3.0|Minor Upgrade|dev on *all platforms*|
|mapclassify|2.7.0|2.8.0|Minor Upgrade|*all*|
|numba_celltree|0.1.8|0.2.0|Minor Upgrade|*all*|
|poppler|24.07.0|24.08.0|Minor Upgrade|*all*|
|pyzmq|26.1.0|26.2.0|Minor Upgrade|*all*|
|s2n|1.4.17|1.5.1|Minor Upgrade|*all envs* on linux-64|
|setuptools|72.1.0|72.2.0|Minor Upgrade|*all*|
|webcolors|24.6.0|24.8.0|Minor Upgrade|dev on *all platforms*|
|zipp|3.19.2|3.20.1|Minor Upgrade|*all*|
|aws-c-auth|0.7.22|0.7.26|Patch Upgrade|*all*|
|aws-c-cal|0.7.1|0.7.3|Patch Upgrade|*all*|
|aws-c-common|0.9.23|0.9.27|Patch Upgrade|*all*|
|aws-c-compression|0.2.18|0.2.19|Patch Upgrade|*all*|
|aws-c-event-stream|0.4.2|0.4.3|Patch Upgrade|*all*|
|aws-c-http|0.8.2|0.8.8|Patch Upgrade|*all*|
|aws-c-io|0.14.10|0.14.18|Patch Upgrade|*all*|
|aws-c-s3|0.6.0|0.6.4|Patch Upgrade|*all*|
|aws-c-sdkutils|0.1.16|0.1.19|Patch Upgrade|*all*|
|aws-crt-cpp|0.27.3|0.27.6|Patch Upgrade|*all*|
|bokeh|3.5.1|3.5.2|Patch Upgrade|*all*|
|dask|2024.8.0|2024.8.1|Patch Upgrade|*all*|
|dask-core|2024.8.0|2024.8.1|Patch Upgrade|*all*|
|dask-expr|1.1.10|1.1.11|Patch Upgrade|*all*|
|distributed|2024.8.0|2024.8.1|Patch Upgrade|*all*|
|gdal|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|importlib-resources|6.4.0|6.4.4|Patch Upgrade|dev on *all platforms*|
|importlib_resources|6.4.0|6.4.4|Patch Upgrade|dev on *all platforms*|
|intel-openmp|2024.2.0|2024.2.1|Patch Upgrade|*all envs* on win-64|
|jupyterlab_widgets|3.0.11|3.0.13|Patch Upgrade|*all*|
|libdrm|2.4.122|2.4.123|Patch Upgrade|{py310, py311} on linux-64|
|libgdal|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-core|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-fits|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-grib|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-hdf4|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-hdf5|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-jp2openjpeg|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-kea|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-netcdf|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-pdf|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-pg|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-postgisraster|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-tiledb|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|libgdal-xls|3.9.1|3.9.2|Patch Upgrade|*all envs* on {linux-64, osx-arm64, win-64}<br/>{py310, py311} on osx-64|
|matplotlib-base|3.9.1|3.9.2|Patch Upgrade|*all envs* on {osx-64, osx-arm64}<br/>{py310, py311} on {linux-64, win-64}|
|orc|2.0.1|2.0.2|Patch Upgrade|*all*|
|pyparsing|3.1.2|3.1.4|Patch Upgrade|*all*|
|pywin32-ctypes|0.2.2|0.2.3|Patch Upgrade|dev on win-64|
|scipy|1.14.0|1.14.1|Patch Upgrade|*all*|
|suitesparse|7.8.0|7.8.2|Patch Upgrade|dev on {linux-64, osx-64, osx-arm64}|
|wayland|1.23.0|1.23.1|Patch Upgrade|{py310, py311} on linux-64|
|widgetsnbextension|4.0.11|4.0.13|Patch Upgrade|*all*|
|types-python-dateutil|2.9.0.20240316|2.9.0.20240821|Other|dev on *all platforms*|
|aws-c-mqtt|h519d897_8|hc4c7fd1_18|Only build string|*all envs* on win-64|
|aws-c-mqtt|hcd6a914_8|h5c8269d_18|Only build string|*all envs* on linux-64|
|aws-c-mqtt|h856d8ab_8|h3e8bf47_18|Only build string|*all envs* on osx-arm64|
|aws-c-mqtt|hf6997d9_8|h03607b6_18|Only build string|*all envs* on osx-64|
|aws-checksums|hd73d8db_7|hf37c103_10|Only build string|*all envs* on osx-64|
|aws-checksums|hea5f451_7|ha1e9ad3_10|Only build string|*all envs* on win-64|
|aws-checksums|h94d0942_7|h85401af_10|Only build string|*all envs* on osx-arm64|
|aws-checksums|he027950_7|h038f3f9_10|Only build string|*all envs* on linux-64|
|aws-sdk-cpp|h46c3b66_0|hf9693f6_5|Only build string|*all envs* on linux-64|
|aws-sdk-cpp|h554caeb_0|hdc2ca5d_5|Only build string|*all envs* on osx-64|
|aws-sdk-cpp|he0aa860_0|hd66f94a_5|Only build string|*all envs* on win-64|
|aws-sdk-cpp|he6360a2_0|h34e68ec_5|Only build string|*all envs* on osx-arm64|
|ceres-solver|hfae76b8_3|ha77e7a2_4|Only build string|dev on linux-64|
|ceres-solver|h4929e67_3|h4929e67_4|Only build string|dev on osx-arm64|
|ceres-solver|h337fa08_3|h337fa08_4|Only build string|dev on osx-64|
|ceres-solver|h0d88682_3|h176f1a4_4|Only build string|dev on win-64|
|gdal|py312h29648be_11|py312h29648be_13|Only build string|{default, dev, py312} on osx-64|
|gettext|h59595ed_2|he02047a_3|Only build string|{default, dev, py312} on linux-64|
|gettext-tools|h59595ed_2|he02047a_3|Only build string|{default, dev, py312} on linux-64|
|glib|h736d271_1|h736d271_2|Only build string|dev on osx-64|
|glib|h7025463_1|h7025463_2|Only build string|{default, dev, py312} on win-64|
|glib|h59d46d9_1|h59d46d9_2|Only build string|dev on osx-arm64|
|glib|h8a4344b_1|h315aac3_2|Only build string|{default, dev, py312} on linux-64|
|glib-tools|h959cb30_1|h959cb30_2|Only build string|dev on osx-64|
|glib-tools|h73ef956_1|h8fdd7da_2|Only build string|{default, dev, py312} on linux-64|
|glib-tools|h8ba3eef_1|h8ba3eef_2|Only build string|dev on osx-arm64|
|glib-tools|h4394cf3_1|h4394cf3_2|Only build string|{default, dev, py312} on win-64|
|libarrow|h27fa419_17_cpu|hfc154c2_23_cpu|Only build string|{default, dev, py312} on osx-64|
|libarrow|h184f21c_17_cpu|hd7a7e94_23_cpu|Only build string|{default, dev, py312} on win-64|
|libarrow|h184f21c_4_cpu|hd7a7e94_10_cpu|Only build string|{py310, py311} on win-64|
|libarrow|h979c047_4_cpu|h9d17f36_10_cpu|Only build string|*all envs* on linux-64|
|libarrow|hc3260fe_4_cpu|h99ce08b_10_cpu|Only build string|{py310, py311} on osx-arm64|
|libarrow|h721ee37_4_cpu|h92d2a6c_10_cpu|Only build string|{py310, py311} on osx-64|
|libarrow|h55eb4e9_17_cpu|h5b12be2_23_cpu|Only build string|{default, dev, py312} on osx-arm64|
|libarrow-acero|hf9b8971_4_cpu|hf9b8971_10_cpu|Only build string|{py310, py311} on osx-arm64|
|libarrow-acero|hf036a51_17_cpu|hf036a51_23_cpu|Only build string|{default, dev, py312} on osx-64|
|libarrow-acero|he0c23c2_17_cpu|he0c23c2_23_cpu|Only build string|{default, dev, py312} on win-64|
|libarrow-acero|he0c23c2_4_cpu|he0c23c2_10_cpu|Only build string|{py310, py311} on win-64|
|libarrow-acero|hac325c4_4_cpu|hac325c4_10_cpu|Only build string|{py310, py311} on osx-64|
|libarrow-acero|he02047a_4_cpu|h5888daf_10_cpu|Only build string|*all envs* on linux-64|
|libarrow-acero|h00cdb27_17_cpu|h00cdb27_23_cpu|Only build string|{default, dev, py312} on osx-arm64|
|libarrow-dataset|hf9b8971_4_cpu|hf9b8971_10_cpu|Only build string|{py310, py311} on osx-arm64|
|libarrow-dataset|hf036a51_17_cpu|hf036a51_23_cpu|Only build string|{default, dev, py312} on osx-64|
|libarrow-dataset|he0c23c2_17_cpu|he0c23c2_23_cpu|Only build string|{default, dev, py312} on win-64|
|libarrow-dataset|he0c23c2_4_cpu|he0c23c2_10_cpu|Only build string|{py310, py311} on win-64|
|libarrow-dataset|hac325c4_4_cpu|hac325c4_10_cpu|Only build string|{py310, py311} on osx-64|
|libarrow-dataset|he02047a_4_cpu|h5888daf_10_cpu|Only build string|*all envs* on linux-64|
|libarrow-dataset|h00cdb27_17_cpu|h00cdb27_23_cpu|Only build string|{default, dev, py312} on osx-arm64|
|libarrow-substrait|hc9a23c6_4_cpu|hf54134d_10_cpu|Only build string|*all envs* on linux-64|
|libarrow-substrait|hc68f6b8_17_cpu|hc68f6b8_23_cpu|Only build string|{default, dev, py312} on osx-arm64|
|libarrow-substrait|hbf8b706_4_cpu|hbf8b706_10_cpu|Only build string|{py310, py311} on osx-arm64|
|libarrow-substrait|hba007a9_4_cpu|hba007a9_10_cpu|Only build string|{py310, py311} on osx-64|
|libarrow-substrait|h85bc590_17_cpu|h85bc590_23_cpu|Only build string|{default, dev, py312} on osx-64|
|libarrow-substrait|h1f0e801_17_cpu|h1f0e801_23_cpu|Only build string|{default, dev, py312} on win-64|
|libarrow-substrait|h1f0e801_4_cpu|h1f0e801_10_cpu|Only build string|{py310, py311} on win-64|
|libasprintf|h661eb56_2|he8f35ee_3|Only build string|{default, dev, py312} on linux-64|
|libasprintf|h5ff76d1_2|hdfe23c8_3|Only build string|dev on osx-64|
|libasprintf|h8fbad5d_2|h8414b35_3|Only build string|dev on osx-arm64|
|libasprintf-devel|h661eb56_2|he8f35ee_3|Only build string|{default, dev, py312} on linux-64|
|libclang-cpp18.1|default_hf981a13_1|default_hf981a13_2|Only build string|{py310, py311} on linux-64|
|libclang13|default_hfc66aa2_1|default_hfc66aa2_2|Only build string|dev on osx-arm64|
|libclang13|default_ha5278ca_1|default_ha5278ca_2|Only build string|*all envs* on win-64|
|libclang13|default_h9ff962c_1|default_h9ff962c_2|Only build string|dev on osx-64|
|libclang13|default_h9def88c_1|default_h9def88c_2|Only build string|*all envs* on linux-64|
|libcxx|heced48a_2|hd876a4e_6|Only build string|*all envs* on osx-64|
|libcxx|h5a72898_2|h3ed4263_6|Only build string|*all envs* on osx-arm64|
|libgdal|h694c41f_11|h694c41f_13|Only build string|{default, dev, py312} on osx-64|
|libgdal-core|h4b9bb65_11|h4b9bb65_13|Only build string|{default, dev, py312} on osx-64|
|libgdal-fits|h5d197d2_11|h5d197d2_13|Only build string|{default, dev, py312} on osx-64|
|libgdal-grib|h385febf_11|h385febf_13|Only build string|{default, dev, py312} on osx-64|
|libgdal-hdf4|h86719f3_11|h86719f3_13|Only build string|{default, dev, py312} on osx-64|
|libgdal-hdf5|h513f0eb_11|h513f0eb_13|Only build string|{default, dev, py312} on osx-64|
|libgdal-jp2openjpeg|hc5f35ca_11|hc5f35ca_13|Only build string|{default, dev, py312} on osx-64|
|libgdal-kea|h3b8d0bf_11|h3b8d0bf_13|Only build string|{default, dev, py312} on osx-64|
|libgdal-netcdf|h3127c03_11|h3127c03_13|Only build string|{default, dev, py312} on osx-64|
|libgdal-pdf|h0da0525_11|ha7d2355_13|Only build string|{default, dev, py312} on osx-64|
|libgdal-pg|h1b48671_11|h1b48671_13|Only build string|{default, dev, py312} on osx-64|
|libgdal-postgisraster|h1b48671_11|h1b48671_13|Only build string|{default, dev, py312} on osx-64|
|libgdal-xls|h597966e_11|h597966e_13|Only build string|{default, dev, py312} on osx-64|
|libgettextpo|h59595ed_2|he02047a_3|Only build string|{default, dev, py312} on linux-64|
|libgettextpo|h5ff76d1_2|hdfe23c8_3|Only build string|dev on osx-64|
|libgettextpo|h8fbad5d_2|h8414b35_3|Only build string|dev on osx-arm64|
|libgettextpo-devel|h59595ed_2|he02047a_3|Only build string|{default, dev, py312} on linux-64|
|libglib|h736d271_1|h736d271_2|Only build string|*all envs* on osx-64|
|libglib|h7025463_1|h7025463_2|Only build string|*all envs* on win-64|
|libglib|h59d46d9_1|h59d46d9_2|Only build string|*all envs* on osx-arm64|
|libglib|h8a4344b_1|h315aac3_2|Only build string|*all envs* on linux-64|
|libintl|h5ff76d1_2|hdfe23c8_3|Only build string|*all envs* on osx-64|
|libintl|h8fbad5d_2|h8414b35_3|Only build string|*all envs* on osx-arm64|
|libintl|h5728263_2|h5728263_3|Only build string|*all envs* on win-64|
|libintl-devel|h5ff76d1_2|hdfe23c8_3|Only build string|dev on osx-64|
|libintl-devel|h8fbad5d_2|h8414b35_3|Only build string|dev on osx-arm64|
|libintl-devel|h5728263_2|h5728263_3|Only build string|{default, dev, py312} on win-64|
|libkml|hbbc8833_1020|hf539b9f_1021|Only build string|*all envs* on linux-64|
|libkml|h00ed6cc_1020|he250239_1021|Only build string|*all envs* on osx-arm64|
|libkml|hfcbc525_1020|h9ee1731_1021|Only build string|*all envs* on osx-64|
|libkml|h538826c_1020|h538826c_1021|Only build string|*all envs* on win-64|
|libllvm18|h9ce406d_1|h9ce406d_2|Only build string|dev on osx-64|
|libllvm18|h8b73ec9_1|h8b73ec9_2|Only build string|*all envs* on linux-64|
|libllvm18|h5090b49_1|h5090b49_2|Only build string|dev on osx-arm64|
|libparquet|h2adadb3_4_cpu|hf1b0f52_10_cpu|Only build string|{py310, py311} on osx-64|
|libparquet|h56531a6_4_cpu|hf0ba9ef_10_cpu|Only build string|{py310, py311} on osx-arm64|
|libparquet|h178134c_17_cpu|ha915800_23_cpu|Only build string|{default, dev, py312} on win-64|
|libparquet|h178134c_4_cpu|ha915800_10_cpu|Only build string|{py310, py311} on win-64|
|libparquet|h904a336_17_cpu|h808e2ea_23_cpu|Only build string|{default, dev, py312} on osx-64|
|libparquet|h9e5060d_4_cpu|h39682fd_10_cpu|Only build string|*all envs* on linux-64|
|libparquet|hcf52c46_17_cpu|h10e5b7d_23_cpu|Only build string|{default, dev, py312} on osx-arm64|
|libxcb|hf2054a2_0|hc9fafa5_1|Only build string|*all envs* on osx-arm64|
|libxcb|hd590300_0|hb9d3cd8_1|Only build string|*all envs* on linux-64|
|libxcb|hcd874cb_0|h013a479_1|Only build string|*all envs* on win-64|
|libxcb|h0dc2134_0|h00291cd_1|Only build string|*all envs* on osx-64|
|llvm-openmp|hde57baf_0|hde57baf_1|Only build string|*all envs* on osx-arm64|
|llvm-openmp|h15ab845_0|h15ab845_1|Only build string|*all envs* on osx-64|
|ncurses|h5846eda_0|hf036a51_1|Only build string|*all envs* on osx-64|
|ncurses|h59595ed_0|he02047a_1|Only build string|*all envs* on linux-64|
|ncurses|hb89a1cb_0|h7bae524_1|Only build string|*all envs* on osx-arm64|
|openssl|h87427d6_2|hd23fc13_3|Only build string|*all envs* on osx-64|
|openssl|h4bc722e_2|hb9d3cd8_3|Only build string|*all envs* on linux-64|
|openssl|hfb2fe0b_2|h8359307_3|Only build string|*all envs* on osx-arm64|
|openssl|h2466b09_2|h2466b09_3|Only build string|*all envs* on win-64|
|pandera-base|pyhd8ed1ab_0|pyhd8ed1ab_1|Only build string|*all*|
|pcre2|h0f59acf_0|hba22ea6_2|Only build string|*all envs* on linux-64|
|pcre2|h7634a1b_0|h7634a1b_2|Only build string|*all envs* on osx-64|
|pcre2|h3d7b363_0|h3d7b363_2|Only build string|*all envs* on win-64|
|pcre2|h297a79d_0|h297a79d_2|Only build string|*all envs* on osx-arm64|
|python_abi|4_cp312|5_cp312|Only build string|{default, dev, py312} on *all platforms*|
|python_abi|4_cp311|5_cp311|Only build string|py311 on *all platforms*|
|python_abi|4_cp310|5_cp310|Only build string|py310 on *all platforms*|
|qt6-main|hbb46ec1_4|hbb46ec1_5|Only build string|{py310, py311} on win-64|
|qt6-main|hb12f9c5_4|hb12f9c5_5|Only build string|{py310, py311} on linux-64|
|tiledb|hc4a707d_5|hc6d05bc_8|Only build string|*all envs* on win-64|
|tiledb|h423fe9d_6|h68e3656_9|Only build string|{default, dev, py312} on osx-64|
|tiledb|h423fe9d_5|h68e3656_8|Only build string|{py310, py311} on osx-64|
|tiledb|hf86781e_5|h33a2d6f_8|Only build string|*all envs* on linux-64|
|tiledb|hbe1479b_5|h183c882_8|Only build string|*all envs* on osx-arm64|
|tzdata|h0c530f3_0|h8827d51_1|Only build string|*all*|
|vc14_runtime|ha82c5b3_20|hcc2c482_20|Only build string|*all envs* on win-64|

[^1]: **Bold** means explicit dependency.
[^2]: Dependency got downgraded.

**Comment by visr** [comment]
TeamCity pixi cannot solve this:

```
14:59:34   ERROR: Unable to locate a modulefile for 'gcc/11.3.0'
14:59:35   pixi 0.22.0
15:00:21     × failed to solve the conda requirements of 'py312' 'osx-64'
15:00:21     ╰─▶ Cannot solve the request because of: qgis >=3.34 cannot be installed
15:00:21         because there are no viable options:
```

I wonder if this is because the pixi version is older on TeamCity.

**Comment by Jingru923** [comment]
I ran `pixi run install-ci` with pixi version of 22.0 (same as TC) locally and got the same error. I ran with pixi newest version and it's error free.

Anyway, I asked Willem to update pixi version to v28.0 for all our Windows agents, and I will ask Maarten to do so for Linux ones

**Comment by deltamarnix** [comment]
@evetion do we still use osx-64, or can we remove it from our list? Since you are using the arm version.

**Comment by evetion** [comment]
I'm fine with removing osx, Github now has free arm runners as well.

**Comment by deltamarnix** [comment]
@visr can you fix my pixi.lock file? pixi crashes every time on my computer.

**Comment by Huite** [comment]
> @visr can you fix my pixi.lock file? pixi crashes every time on my computer.

Did you try deleting the .pixi directory in the project?

**Comment by deltamarnix** [comment]
> > @visr can you fix my pixi.lock file? pixi crashes every time on my computer.
> 
> Did you try deleting the .pixi directory in the project?

Yes removed the .pixi folder and the lock file, but still got it crashing after ~10 minutes

**Comment by visr** [comment]
Pixi doesn't seem to appreciate having to resolve with more than one channel, `channels = ["conda-forge/label/qgis_ltr", "conda-forge"]`. My laptop has been trying to resolve it for quite a while and is getting quite hot. I just killed it because I was afraid it would take off.

Now that we have some automatic testing of QGIS LTR via Docker in #1774, perhaps we should leave the QGIS in pixi to the latest release. As such we'll have some automatic testing for both versions. Would still be good to separately remove osx-64 if we don't use it.

**Comment by visr** [comment]
There's a conflict in pixi.lock. What commands did you use to run this? Does this only remove osx-64 or also update dependencies?

Are you planning on fixing the Docker LTR tag in a separate issue?

**Comment by deltamarnix** [comment]
> There's a conflict in pixi.lock. What commands did you use to run this? Does this only remove osx-64 or also update dependencies?
> 
> Are you planning on fixing the Docker LTR tag in a separate issue?

I talked with @evetion about the LTR version. But if I change it to qgis/ltr, then we will automatically upgrade to the latest LTR every x years. @evetion didn't know if that was desirable.

I did a `pixi update` as well, because it didn't seem to "just resolve" the lock file for me when I removed osx.

**Comment by visr** [comment]
Yeah probably 3.34 is better than LTR. Our docs and plugin metadata also say 3.34.

**Comment by visr** [comment]
Closing in favor of #1777.

**Pull request closed without merging**
