### PR TITLE
Fractional flow validation

### PR DESCRIPTION
**Pull request by SouthEndMusic**
Fixes https://github.com/Deltares/Ribasim/issues/413.

### CODE REVIEW

**Comment by SouthEndMusic** [comment]
Why does that only fail on Ubuntu 🤔

**Review by visr — APPROVED** [review]
The Ubuntu fail is quite strange. I restarted it but still the same issue. It didn't write the new test model this PR adds, though it should since it is written in conftest.py.

The PR seems good to me, nice to have these extra checks in place.

One thing about the logging of errors in `valid_fractional_flow`. I know this pattern is used elsewhere as well, but I see no benefit over collecting error messages in a vector and logging them later, versus logging them directly, and setting a boolean to true, to mark the invalid model. The function `valid_pid_connectivity` above uses this. When an error is logged by default it notes where in the source code this is coming from. This will then also be a more useful location as well.

```
┌ Error: this is wrong
└ @ Main REPL[3]:1
┌ Error: that is wrong
└ @ Main REPL[3]:1
```

**Comment by SouthEndMusic** [comment]
@visr isn't it bad to have this fail on main?

**Comment by visr** [comment]
Yes it is. We could merge it though to double check if it also errors on main. If it does, we can skip the test on Ubuntu while we figure out the issue.

**Pull request merged**
