### PR TITLE
Decrease relative tolerance from 1e-5 to 1e-7

### LINKED ISSUE #1851: [bug] Terminals sometimes "leak" water
I hit this during the implementation of #1849, where edges to Terminals have negative flows when checked in `update_cumulative_flows!` using the flow from `flow_update_on_edge`. For example in the HWS model I get the following:

```
┌ Warning: Terminal #5415 has flow of -338.54177272319794 at 6.862248444895375e6 for a timestep of 91.35735275302858
└ @ Ribasim /Users/evetion/code/Ribasim/core/src/callback.jl:205
┌ Warning: Terminal #5415 has flow of -85.64921969175339 at 6.862339802248128e6 for a timestep of 91.35735275302858
└ @ Ribasim /Users/evetion/code/Ribasim/core/src/callback.jl:205
┌ Warning: Terminal #5415 has flow of -8.970432549715042 at 6.862431159600881e6 for a timestep of 91.35735275302858
└ @ Ribasim /Users/evetion/code/Ribasim/core/src/callback.jl:205
┌ Warning: Terminal #5415 has flow of -0.8940373957157135 at 6.862489481604243e6 for a timestep of 58.32200336178765
└ @ Ribasim /Users/evetion/code/Ribasim/core/src/callback.jl:205
┌ Warning: Terminal #5415 has flow of -0.9066413938999176 at 6.862868324295173e6 for a timestep of 378.8426909304897
└ @ Ribasim /Users/evetion/code/Ribasim/core/src/callback.jl:205
┌ Warning: Terminal #5415 has flow of -0.1415431797504425 at 6.863247166986104e6 for a timestep of 378.8426909304897
└ @ Ribasim /Users/evetion/code/Ribasim/core/src/callback.jl:205
┌ Warning: Terminal #5415 has flow of -0.06280365586280823 at 6.8643238840039205e6 for a timestep of 1076.7170178166448
└ @ Ribasim /Users/evetion/code/Ribasim/core/src/callback.jl:205
┌ Warning: Terminal #5415 has flow of -0.009804785251617432 at 6.865400601021737e6 for a timestep of 1076.7170178166448
└ @ Ribasim /Users/evetion/code/Ribasim/core/src/callback.jl:205
┌ Warning: Terminal #5415 has flow of -3.9677118062973022 at 6.882244989985872e6 for a timestep of 0.059130550789141804
└ @ Ribasim /Users/evetion/code/Ribasim/core/src/callback.jl:205
┌ Warning: Terminal #5415 has flow of -0.628738522529602 at 6.882245101221386e6 for a timestep of 0.11123551420152002
└ @ Ribasim /Users/evetion/code/Ribasim/core/src/callback.jl:205
┌ Warning: Terminal #5415 has flow of -1.5169505487529635e6 at 8.982259552166957e6 for a timestep of 3340.4478330416605
└ @ Ribasim /Users/evetion/code/Ribasim/core/src/callback.jl:205
┌ Warning: Terminal #5415 has flow of -2858.7084048986435 at 9.849623705491675e6 for a timestep of 23.70549167560891
└ @ Ribasim /Users/evetion/code/Ribasim/core/src/callback.jl:205
...
```

This is the Terminal at Herentals in the HWS model with an Outlet(!) before it (the only Terminal one to show such behaviour). I can imagine this happens during smaller timesteps to balance the problem, and you'll never see this on the larger saveat timesteps. Given the rather large flows/timesteps in the above, this should be investigated (could also be a bug in the code to check such flows).

### LINKED ISSUE #1863: Error in exchange waterbalance coupler Ribasim-MF-MS
After the refactor in waterbalance error #1808 test in coupler are giving unexpected results. Could be related to the changes in how fluxes are integrated on Ribasim side.

Possibly the same as #1851.

### PR DESCRIPTION
**Pull request by visr**
With #1819 the state goes further away from 0 with time. That means we rely more on the relative tolerance than the absolute tolerance, see the [SciML docs](https://docs.sciml.ai/DiffEqDocs/stable/basics/faq/#What-does-tolerance-mean-and-how-much-error-should-I-expect) on the topic. Hence I found that reducing the `abstol` had no effect, but reducing the default `reltol` by two orders of magnitude is enough to get only negligible leaky Terminals with occasional very brief leaks of 1e-8 m3/s. It is also enough to minimize the infiltration error to acceptable levels as can be seen in https://github.com/Deltares/Ribasim/issues/1863#issuecomment-2397302808.

~~For HWS this slows down simulation from 9.1s to 12.3s, which isn't too bad for a two orders of magnitude reduction in relative tolerance.~~ Rechecking HWS performance gives a speedup! 12.4s for 1e-8, 8.1s for 1e-7, 10.2s for 1e-6. So 1e-7 seems optimal. Not sure what went wrong last time, but this seems pretty consistent. This is with both absolute and relative set to the same number.

Fixes #1851
Fixes #1863

### CODE REVIEW

**Comment by visr** [comment]
Perhaps for simplicity/consistency we should set the abstol to 1e-7 as well.

**Comment by Huite** [comment]
> Hence I found that reducing the abstol had no effect, but reducing the default reltol by two orders of magnitude is enough to get only negligible leaky Terminals with occasional very brief leaks of 1e-8 m3/s.

This seems very obvious in retrospect, indeed.
It's a bit unintuitive coming from a regular head/storage formulation, since those are clearly more bounded.
Resetting to 0 (maybe not every `saveat`, but maybe every change of boundary condition), since the solver is getting a shock in those cases anyway.

**Comment by visr** [comment]
It's hard to find a good time for resetting though that doesn't cause issues for BMI, which currently assumes there is never any resetting. Also saveat can be infinite. Not resetting also makes it easy to get the total water balance over time.

**Comment by visr** [comment]
In what way meaningless? Do you mean floating point accuracy issues? Perhaps a yearly reset would be predictable enough for BMI to work around, although the BMI driver would have to be calendar aware.

**Comment by Huite** [comment]
Let's say you have a flow boundary constantly pumping in water and the flow on the edge accumulates monotonically, with 1000 m3/d; let's further assume that flow is (nigh) steady-state.

At t=1 day, flow = 1000; relative tolerance value is `reltol * 1000`;
At t=1000 days, flow = 100 000 days; relative tolerance value is `reltol * 1_000_000`.

I.e. the tolerance has effectively become a 1000 times relaxed, right? While the physical meaning of the model remains the same.

**Pull request merged**
