### PR TITLE
Re-enable edge validation

### PR DESCRIPTION
**Pull request by visr**
This validation was inadvertently not called anymore. This now adds a test to make sure that doesn't happen again.

@SouthEndMusic tests fail since an invalid connection slipped in since, do you want to take over this PR to fix that?

```
┌ Error: Cannot connect a basin to a basin.
│   edge_id = 0
│   id_src = #2
│   id_dst = #4
└ @ Ribasim D:\Ribasim\core\src\validation.jl:450
Error in testset "Allocation objective types" on worker 24444:
Error During Test at D:\Ribasim\core\test\allocation_test.jl:27
```

### CODE REVIEW

**Comment by visr** [comment]
Thanks @SouthEndMusic, your changes look good to me. I cannot approve the PR though :)

@Hofer-Julian do you have any idea why this fails pre-commit?

```
trim trailing whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing .teamcity/Ribasim_Ribasim/buildTypes/Ribasim_Ribasim_MakeGitHubRelease.xml
```

The `end-of-file-fixer` explicitly excludes `.teamcity`:

```
        id: end-of-file-fixer
        exclude: '.teamcity'
```

**Comment by Hofer-Julian** [comment]
> Thanks @SouthEndMusic, your changes look good to me. I cannot approve the PR though :)
> 
> @Hofer-Julian do you have any idea why this fails pre-commit?
> 
> ```
> trim trailing whitespace.................................................Failed
> - hook id: trailing-whitespace
> - exit code: 1
> - files were modified by this hook
> 
> Fixing .teamcity/Ribasim_Ribasim/buildTypes/Ribasim_Ribasim_MakeGitHubRelease.xml
> ```
> 
> The `end-of-file-fixer` explicitly excludes `.teamcity`:
> 
> ```
>         id: end-of-file-fixer
>         exclude: '.teamcity'
> ```

Maybe, it needs a glob?

**Comment by visr** [comment]
> Maybe it needs a glob?

No I wasn't looking properly. It was trailing-whitespace, which doesn't exclude .teamcity. We could exclude it of course, but the TeamCity UI doesn't add them, so we probably shouldn't.

**Review by SouthEndMusic — APPROVED** [review]
LGTM (if I say so myself)

**Pull request merged**
