### PR TITLE
Try to fix missing import of pandera in Delwaq testing

### PR DESCRIPTION
**Pull request by evetion**
To fix failing Delwaq pipelines.

### CODE REVIEW

**Comment by visr** [comment]
Hmm, wrapt was already in our environment hence the lock file didn't change, so it's not surprising this doesn't do anything, the same error still shows:

```
  .pixi\envs\dev\Lib\site-packages\pandera\__init__.py:31: in <module>
17:52:40       from pandera.decorators import check_input, check_io, check_output, check_types
17:52:40   .pixi\envs\dev\Lib\site-packages\pandera\decorators.py:25: in <module>
17:52:40       import wrapt
```

**Comment by evetion** [comment]
Yeah, I had a sinking feeling when I saw no changes to the lock file. I'm at a loss of what's happening, my gut now says that the wrapt installation is corrupt on some Windows agents (without a clear pattern though) and that pixi doesn't detect that. How it would become corrupt (pandera nor wrapt had an update in recent times) is a mystery, but I am more suspicious of the Teamcity agents than pixi?

**Comment by visr** [comment]
Can this be closed?

**Comment by evetion** [comment]
Hmm, it's seems to be one agent failing intermittently. And most PRs have this as a failing test, so this could still be useful?

**Review by visr — APPROVED** [review]
Fine with me to merge this if you prefer, though I don't see Delwaq failing on the latest PRs, We would need an issue to remind us to remove this again though, to avoid a situation like #1766 where a dependency we don't use blocks things.

**Comment by evetion** [comment]
Ok, let's close for now, since main has been green for a bit. It's mostly agent c-teamcity22092, I've cleaned the source on that agent, let's see what happens.

**Pull request closed without merging**
