### PR TITLE
Split usage to separate pages

### PR DESCRIPTION
**Pull request by visr**
Part of https://github.com/Deltares/Ribasim/issues/207.

This moves the information out of the usage page to separate pages. For some node types I added information on the top of the page, others already had this, and I just moved it out of the schema section.

The pages are grouped together in the sidebar. By default they are not collapsed. This can be controlled by the collapse level in Quarto, see https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation.

image

Since this is already quite big, I prefer to not add the equations in this step as well.

### CODE REVIEW

**Comment by evetion** [comment]
Keep in mind the https://docs.divio.com/documentation-system/structure/ system to refactor the documentation.

**Review by evetion — APPROVED** [review]

**Comment by visr** [comment]
Yeah I need to think a bit about that. I see these pages mainly as reference.

https://diataxis.fr/

**Comment by evetion** [comment]
Based on our discussion yesterday, the validation table which node can connect to what would be greatly helped by mermaid diagrams on each of the node pages that shows all possible connections and flow directions.

Another idea, can we put the styling icon from QGIS/testmodels to the individual nodepages?

**Comment by visr** [comment]
Yeah I think these are both good ideas, perhaps add them to #207?

My idea was that it would be nice that pretty much anything related to node X should be on the X page. Therefore users should not have to go to a separate page to figure out what they can connect it to.

**Pull request merged**
