### PR TITLE
Regression test 1/2

### PR DESCRIPTION
**Pull request by Jingru923**
Fixes the test part of  #462 , the update of CI/CD will come in a different PR (will be named "Regression test 2/2")
Now if you enter `pixi run test-ribasim-regression` terminal, regression tests are run.

### CODE REVIEW

**Comment by visr** [comment]
I want to avoid checking the reference results into this repository. For these models they may still be small, but not for the larger models. And they will need to be upgraded every now and then.

@deltamarnix do you know a good solution? It's a bit like the hosting of images for the docs of #1. I guess we could use the hack of uploading assets into https://github.com/visr/ribasim-artifacts/releases. Or use S3 like we did before for hosting nightlies: https://github.com/Deltares/Ribasim/issues/105#issuecomment-1482532408.

**Comment by Jingru923** [comment]
In my opinion, having the reference result somewhere that can be accessed by TeamCity seems reasonable.

**Comment by visr** [comment]
@Manangka suggests requesting self hosted [MinIO](https://publicwiki.deltares.nl/display/GIT/MinIO) storage for this.

**Comment by deltamarnix** [comment]
> @Manangka suggests requesting self hosted [MinIO](https://publicwiki.deltares.nl/display/GIT/MinIO) storage for this.

I agree. Test data should be in our MinIO buckets, just like Delft3D does.

**Pull request closed without merging**
