### PR TITLE
Fix development tools

### PR DESCRIPTION
**Pull request by deltamarnix**
* Restore open-vscode.bat to use with Quarto and Julia
* Fix mypy paths for qgis
* Insert new line on save

### CODE REVIEW

**Review by visr — APPROVED** [review]
This looks good, thanks! Looking at the changes in the lock file, this downgrades a lot of packages, e.g. numpy back to 1, pyarrow back to 14. I guess that is all because the QGIS LTR build is not compatible with those yet? I do hope that new LTR builds will fix this because otherwise we won't know when new downstream packages break Ribasim Python. We can also consider therefore sticking with the latest QGIS release in dev, and perhaps testing LTR separately.

**Comment by deltamarnix** [comment]
> This looks good, thanks! Looking at the changes in the lock file, this downgrades a lot of packages, e.g. numpy back to 1, pyarrow back to 14. I guess that is all because the QGIS LTR build is not compatible with those yet? I do hope that new LTR builds will fix this because otherwise we won't know when new downstream packages break Ribasim Python. We can also consider therefore sticking with the latest QGIS release in dev, and perhaps testing LTR separately.

If that is the case, maybe it's better to resolve them in separate environments. Developing QGIS is different than developing Ribasim python. It will even make us use a different python version for that specific piece of code, right?

**Comment by visr** [comment]
Yeah perhaps a separate environment would be better. I didn't check the python version in this lockfile, but the conda-forge QGIS builds do allow a much newer Python compared to the qgis.org builds.

**Comment by deltamarnix** [comment]
@visr I have removed the QGIS fixation, as QGIS tests and Delwaq tests were failing.

**Pull request merged**
