### PR TITLE
Move export QUARTO_PYTHON to env_setup

### PR DESCRIPTION
**Pull request by deltamarnix**
@Hofer-Julian Not sure how you used to test this. Was something broken with the normal python that was used by Quarto?

### CODE REVIEW

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian Not sure how you used to test this. Was something broken with the normal python that was used by Quarto?

It detected the wrong Python on windows. Unfortunately quarto uses pylauncher on Windows instead of simply using the first python in Path. Feel free to experiment with removing it, maybe it's fixed nowadays.

**Comment by Hofer-Julian** [comment]
This also means that you only have to set the env var on windows. You can leave UNIX alone

**Comment by deltamarnix** [comment]
@Hofer-Julian How do I see that it 'detects the wrong python'? What was going wrong?

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian How do I see that it 'detects the wrong python'? What was going wrong?

Windows adds a dummy python on every machine, which does nothing but redirecting you to the windows apps store. On my machine, it detected that.

**Comment by deltamarnix** [comment]
So you're saying it doesn't detect python at all and therefore doesn't start the preview.

**Comment by Hofer-Julian** [comment]
I've tried it again, and without `QUARTO_PYTHON` it still breaks for me:

```
  File "C:\checkouts\github.com\Deltares\Ribasim\.pixi\env\Library\share\quarto\jupyter\jupyter.py", line 21,
in <module>
    from notebook import notebook_execute, RestartKernel
  File "C:\checkouts\github.com\Deltares\Ribasim\.pixi\env\Library\share\quarto\jupyter\notebook.py", line 17,
 in <module>
    import nbformat
ModuleNotFoundError: No module named 'nbformat'
Python 3 installation:
  Version: 3.10.10 (Conda)
  Path: C:/Users/hofer_jn/AppData/Local/mambaforge/python.exe
  Jupyter: (None)
```

**Comment by deltamarnix** [comment]
@Hofer-Julian Can you tell me what is "it"? What are you running?

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian Can you tell me what is "it"? What are you running?

Fair enough. I ran `pixi run quarto-render`. During the run it picked up the wrong Python.

**Comment by deltamarnix** [comment]
@Hofer-Julian This doesn't happen on my machine, because I don't have another python installed. Could you give it another go? I have changed it so that `QUARTO_PYTHON` is set during the activation of pixi.

**Review by Hofer-Julian — APPROVED** [review]
The current changes work fine on my machine.
It is also a bit cleaner now. Thanks, @deltamarnix!

**Pull request merged**
