### PR TITLE
Remove using S for storage (use u)

### PR DESCRIPTION
**Pull request by SouthEndMusic**
Fixes https://github.com/Deltares/Ribasim/issues/968.

### CODE REVIEW

**Comment by Jingru923** [comment]
I see the new letter you are using is also used somewhere. For example, in equation section, equation (1) has also 'u'. In numerical considerations, equation (1), there is also 'u'. 
For me, I think the doc is less confusing than before, it's improving. However, how do you think about the overlapping of 'u'? @SouthEndMusic

**Comment by SouthEndMusic** [comment]
@Jingru923 these all refer to the same $u$, which is the state vector of the model.

**Comment by Jingru923** [comment]
So the storages are states?

**Comment by SouthEndMusic** [comment]
> So the storages are states?

Indeed, the system of differential equations which is solved by the Ribasim core is in terms of the storages of the basins (and the integral term of the PID controller).

**Review by Jingru923 — APPROVED** [review]

**Pull request merged**
