### PR TITLE
Adding Manning resistance equation test

### PR DESCRIPTION
**Pull request by SouthEndMusic**
Fixes part of https://github.com/Deltares/Ribasim/issues/206.

### CODE REVIEW

**Comment by SouthEndMusic** [comment]
Not sure why all those previous commits are included here?

**Comment by Hofer-Julian** [comment]
> Not sure why all those previous commits are included here?

I assume because your PR targets `Test-node-equations-feature` rather than `main`.
Was that intended?

**Comment by SouthEndMusic** [comment]
Yes that was intended because this is the feature  branch for equation testing (I'm giving that up after this). My chances still need review though, although it doesn't say so.

**Comment by Hofer-Julian** [comment]
> Yes that was intended because this is the feature branch for equation testing (I'm giving that up after this). My chances still need review though, although it doesn't say so.

What you can try is to merge main into the feature branch.
If that doesn't help with the big diff then we have to look for alternatives.

**Review by Hofer-Julian — APPROVED** [review]
One minor comment, apart from that looks good to me!

**Pull request merged**
